#!/bin/bash
cyclone read1.scm
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt && \
./read1 > out.txt && tail out.txt  
