## Name of the main module
APP = sprinkles

## Web server configuration
WEB_DIR = /usr/share/nginx/html
APP_WEB_SUBDIR = cyclone

## Cyclone compiler configuration
CYCLONE = cyclone
CYCLONE_DIR = /usr/local/share/cyclone
