/**
 ** This file was automatically generated by the Cyclone scheme compiler
 ** http://justinethier.github.io/cyclone/
 **
 ** (c) 2014-2018 Justin Ethier
 ** Version 0.9.4 
 **
 **/

#define closcall1(td, clo,a1) \
if (type_is_pair_prim(clo)) { \
   Cyc_apply(td, 0, (closure)(a1), clo); \
} else { \
   ((clo)->fn)(td, 1, clo,a1);\
}
#define return_closcall1(td, clo,a1) { \
 char top; \
 if (stack_overflow(&top, (((gc_thread_data *)data)->stack_limit))) { \
     object buf[1]; buf[0] = a1;\
     GC(td, clo, buf, 1); \
     return; \
 } else {\
     closcall1(td, (closure) (clo),a1); \
     return;\
 } \
}

#define return_direct1(td, _fn,a1) { \
 char top; \
 if (stack_overflow(&top, (((gc_thread_data *)data)->stack_limit))) { \
     object buf[1]; buf[0] = a1; \
     mclosure0(c1, (function_type) _fn); \
     GC(td, &c1, buf, 1); \
     return; \
 } else { \
     (_fn)(td, 1, (closure)_fn,a1); \
 }}

#define return_direct_with_clo1(td, clo, _fn,a1) { \
 char top; \
 if (stack_overflow(&top, (((gc_thread_data *)data)->stack_limit))) { \
     object buf[1]; buf[0] = a1;\
     GC(td, clo, buf, 1); \
     return; \
 } else { \
     (_fn)(td, 1, (closure)(clo),a1); \
 }}

#define closcall2(td, clo,a1,a2) \
if (type_is_pair_prim(clo)) { \
   Cyc_apply(td, 1, (closure)(a1), clo,a2); \
} else { \
   ((clo)->fn)(td, 2, clo,a1,a2);\
}
#define return_closcall2(td, clo,a1,a2) { \
 char top; \
 if (stack_overflow(&top, (((gc_thread_data *)data)->stack_limit))) { \
     object buf[2]; buf[0] = a1;buf[1] = a2;\
     GC(td, clo, buf, 2); \
     return; \
 } else {\
     closcall2(td, (closure) (clo),a1,a2); \
     return;\
 } \
}

#define return_direct2(td, _fn,a1,a2) { \
 char top; \
 if (stack_overflow(&top, (((gc_thread_data *)data)->stack_limit))) { \
     object buf[2]; buf[0] = a1;buf[1] = a2; \
     mclosure0(c1, (function_type) _fn); \
     GC(td, &c1, buf, 2); \
     return; \
 } else { \
     (_fn)(td, 2, (closure)_fn,a1,a2); \
 }}

#define return_direct_with_clo2(td, clo, _fn,a1,a2) { \
 char top; \
 if (stack_overflow(&top, (((gc_thread_data *)data)->stack_limit))) { \
     object buf[2]; buf[0] = a1;buf[1] = a2;\
     GC(td, clo, buf, 2); \
     return; \
 } else { \
     (_fn)(td, 2, (closure)(clo),a1,a2); \
 }}

#define closcall3(td, clo,a1,a2,a3) \
if (type_is_pair_prim(clo)) { \
   Cyc_apply(td, 2, (closure)(a1), clo,a2,a3); \
} else { \
   ((clo)->fn)(td, 3, clo,a1,a2,a3);\
}
#define return_closcall3(td, clo,a1,a2,a3) { \
 char top; \
 if (stack_overflow(&top, (((gc_thread_data *)data)->stack_limit))) { \
     object buf[3]; buf[0] = a1;buf[1] = a2;buf[2] = a3;\
     GC(td, clo, buf, 3); \
     return; \
 } else {\
     closcall3(td, (closure) (clo),a1,a2,a3); \
     return;\
 } \
}

#define return_direct3(td, _fn,a1,a2,a3) { \
 char top; \
 if (stack_overflow(&top, (((gc_thread_data *)data)->stack_limit))) { \
     object buf[3]; buf[0] = a1;buf[1] = a2;buf[2] = a3; \
     mclosure0(c1, (function_type) _fn); \
     GC(td, &c1, buf, 3); \
     return; \
 } else { \
     (_fn)(td, 3, (closure)_fn,a1,a2,a3); \
 }}

#define return_direct_with_clo3(td, clo, _fn,a1,a2,a3) { \
 char top; \
 if (stack_overflow(&top, (((gc_thread_data *)data)->stack_limit))) { \
     object buf[3]; buf[0] = a1;buf[1] = a2;buf[2] = a3;\
     GC(td, clo, buf, 3); \
     return; \
 } else { \
     (_fn)(td, 3, (closure)(clo),a1,a2,a3); \
 }}

#define closcall5(td, clo,a1,a2,a3,a4,a5) \
if (type_is_pair_prim(clo)) { \
   Cyc_apply(td, 4, (closure)(a1), clo,a2,a3,a4,a5); \
} else { \
   ((clo)->fn)(td, 5, clo,a1,a2,a3,a4,a5);\
}
#define return_closcall5(td, clo,a1,a2,a3,a4,a5) { \
 char top; \
 if (stack_overflow(&top, (((gc_thread_data *)data)->stack_limit))) { \
     object buf[5]; buf[0] = a1;buf[1] = a2;buf[2] = a3;buf[3] = a4;buf[4] = a5;\
     GC(td, clo, buf, 5); \
     return; \
 } else {\
     closcall5(td, (closure) (clo),a1,a2,a3,a4,a5); \
     return;\
 } \
}

#define return_direct5(td, _fn,a1,a2,a3,a4,a5) { \
 char top; \
 if (stack_overflow(&top, (((gc_thread_data *)data)->stack_limit))) { \
     object buf[5]; buf[0] = a1;buf[1] = a2;buf[2] = a3;buf[3] = a4;buf[4] = a5; \
     mclosure0(c1, (function_type) _fn); \
     GC(td, &c1, buf, 5); \
     return; \
 } else { \
     (_fn)(td, 5, (closure)_fn,a1,a2,a3,a4,a5); \
 }}

#define return_direct_with_clo5(td, clo, _fn,a1,a2,a3,a4,a5) { \
 char top; \
 if (stack_overflow(&top, (((gc_thread_data *)data)->stack_limit))) { \
     object buf[5]; buf[0] = a1;buf[1] = a2;buf[2] = a3;buf[3] = a4;buf[4] = a5;\
     GC(td, clo, buf, 5); \
     return; \
 } else { \
     (_fn)(td, 5, (closure)(clo),a1,a2,a3,a4,a5); \
 }}

#include "cyclone/types.h"
object __glo_this_91scheme_91implementation_91name = NULL;
object __glo_run_91r7rs_91benchmark = NULL;
object __glo_hide = NULL;
object __glo_main = NULL;
object __glo_iterative_91div2 = NULL;
object __glo_create_91n = NULL;
extern object __glo_member_scheme_base;
extern object __glo_assoc_scheme_base;
extern object __glo_cons_91source_scheme_base;
extern object __glo_syntax_91rules_scheme_base;
extern object __glo_letrec_85_scheme_base;
extern object __glo_guard_scheme_base;
extern object __glo_guard_91aux_scheme_base;
extern object __glo_define_91record_91type_scheme_base;
extern object __glo_record_127_scheme_base;
extern object __glo_is_91a_127_scheme_base;
extern object __glo_register_91simple_91type_scheme_base;
extern object __glo_make_91type_91predicate_scheme_base;
extern object __glo_make_91constructor_scheme_base;
extern object __glo_make_91getter_scheme_base;
extern object __glo_make_91setter_scheme_base;
extern object __glo_slot_91ref_scheme_base;
extern object __glo_slot_91set_67_scheme_base;
extern object __glo_type_91slot_91offset_scheme_base;
extern object __glo_receive_scheme_base;
extern object __glo_abs_scheme_base;
extern object __glo_max_scheme_base;
extern object __glo_min_scheme_base;
extern object __glo_modulo_scheme_base;
extern object __glo_floor_91remainder_scheme_base;
extern object __glo_even_127_scheme_base;
extern object __glo_exact_91integer_127_scheme_base;
extern object __glo_exact_91integer_91sqrt_scheme_base;
extern object __glo_exact_127_scheme_base;
extern object __glo_inexact_127_scheme_base;
extern object __glo_odd_127_scheme_base;
extern object __glo_complex_127_scheme_base;
extern object __glo_rational_127_scheme_base;
extern object __glo_bignum_127_scheme_base;
extern object __glo_gcd_scheme_base;
extern object __glo_lcm_scheme_base;
extern object __glo_quotient_scheme_base;
extern object __glo_remainder_scheme_base;
extern object __glo_truncate_91quotient_scheme_base;
extern object __glo_truncate_91remainder_scheme_base;
extern object __glo_truncate_95_scheme_base;
extern object __glo_floor_91quotient_scheme_base;
extern object __glo_floor_91remainder_scheme_base;
extern object __glo_floor_95_scheme_base;
extern object __glo_square_scheme_base;
extern object __glo_expt_scheme_base;
extern object __glo_call_91with_91current_91continuation_scheme_base;
extern object __glo_call_95cc_scheme_base;
extern object __glo_call_91with_91values_scheme_base;
extern object __glo_dynamic_91wind_scheme_base;
extern object __glo_values_scheme_base;
extern object __glo_char_123_127_scheme_base;
extern object __glo_char_121_127_scheme_base;
extern object __glo_char_125_127_scheme_base;
extern object __glo_char_121_123_127_scheme_base;
extern object __glo_char_125_123_127_scheme_base;
extern object __glo_string_123_127_scheme_base;
extern object __glo_string_121_127_scheme_base;
extern object __glo_string_121_123_127_scheme_base;
extern object __glo_string_125_127_scheme_base;
extern object __glo_string_125_123_127_scheme_base;
extern object __glo_foldl_scheme_base;
extern object __glo_foldr_scheme_base;
extern object __glo_not_scheme_base;
extern object __glo_list_127_scheme_base;
extern object __glo_zero_127_scheme_base;
extern object __glo_positive_127_scheme_base;
extern object __glo_negative_127_scheme_base;
extern object __glo_append_scheme_base;
extern object __glo__list_scheme_base;
extern object __glo_make_91list_scheme_base;
extern object __glo_list_91copy_scheme_base;
extern object __glo_map_scheme_base;
extern object __glo_Cyc_91map_91loop_911_scheme_base;
extern object __glo_Cyc_91for_91each_91loop_911_scheme_base;
extern object __glo_for_91each_scheme_base;
extern object __glo_list_91tail_scheme_base;
extern object __glo_list_91ref_scheme_base;
extern object __glo_list_91set_67_scheme_base;
extern object __glo_reverse_scheme_base;
extern object __glo_boolean_123_127_scheme_base;
extern object __glo_symbol_123_127_scheme_base;
extern object __glo_Cyc_91obj_123_127_scheme_base;
extern object __glo_vector_scheme_base;
extern object __glo_vector_91append_scheme_base;
extern object __glo_vector_91copy_scheme_base;
extern object __glo_vector_91copy_67_scheme_base;
extern object __glo_vector_91fill_67_scheme_base;
extern object __glo_vector_91_125list_scheme_base;
extern object __glo_vector_91_125string_scheme_base;
extern object __glo_vector_91map_scheme_base;
extern object __glo_vector_91for_91each_scheme_base;
extern object __glo_make_91string_scheme_base;
extern object __glo_string_scheme_base;
extern object __glo_string_91copy_scheme_base;
extern object __glo_string_91copy_67_scheme_base;
extern object __glo_string_91fill_67_scheme_base;
extern object __glo_string_91_125list_scheme_base;
extern object __glo_string_91_125vector_scheme_base;
extern object __glo_string_91map_scheme_base;
extern object __glo_string_91for_91each_scheme_base;
extern object __glo_make_91parameter_scheme_base;
extern object __glo_current_91output_91port_scheme_base;
extern object __glo_current_91input_91port_scheme_base;
extern object __glo_current_91error_91port_scheme_base;
extern object __glo_call_91with_91port_scheme_base;
extern object __glo_error_91object_127_scheme_base;
extern object __glo_error_91object_91message_scheme_base;
extern object __glo_error_91object_91irritants_scheme_base;
extern object __glo_error_scheme_base;
extern object __glo_raise_scheme_base;
extern object __glo_raise_91continuable_scheme_base;
extern object __glo_with_91handler_scheme_base;
extern object __glo_with_91exception_91handler_scheme_base;
extern object __glo_Cyc_91add_91exception_91handler_scheme_base;
extern object __glo_Cyc_91remove_91exception_91handler_scheme_base;
extern object __glo_newline_scheme_base;
extern object __glo_write_91char_scheme_base;
extern object __glo_write_91string_scheme_base;
extern object __glo_flush_91output_91port_scheme_base;
extern object __glo_peek_91char_scheme_base;
extern object __glo_read_91char_scheme_base;
extern object __glo_read_91line_scheme_base;
extern object __glo_read_91string_scheme_base;
extern object __glo_input_91port_127_scheme_base;
extern object __glo_output_91port_127_scheme_base;
extern object __glo_input_91port_91open_127_scheme_base;
extern object __glo_output_91port_91open_127_scheme_base;
extern object __glo_get_91output_91string_scheme_base;
extern object __glo_open_91output_91string_scheme_base;
extern object __glo_open_91input_91string_scheme_base;
extern object __glo_get_91output_91bytevector_scheme_base;
extern object __glo_open_91input_91bytevector_scheme_base;
extern object __glo_open_91output_91bytevector_scheme_base;
extern object __glo_features_scheme_base;
extern object __glo_Cyc_91version_scheme_base;
extern object __glo_any_scheme_base;
extern object __glo_every_scheme_base;
extern object __glo_and_scheme_base;
extern object __glo_or_scheme_base;
extern object __glo_let_scheme_base;
extern object __glo_let_85_scheme_base;
extern object __glo_letrec_scheme_base;
extern object __glo_let_85_91values_scheme_base;
extern object __glo_let_91values_scheme_base;
extern object __glo_begin_scheme_base;
extern object __glo__case_scheme_base;
extern object __glo_cond_scheme_base;
extern object __glo_cond_91expand_scheme_base;
extern object __glo__do_scheme_base;
extern object __glo_when_scheme_base;
extern object __glo_unless_scheme_base;
extern object __glo_quasiquote_scheme_base;
extern object __glo_floor_scheme_base;
extern object __glo_ceiling_scheme_base;
extern object __glo_truncate_scheme_base;
extern object __glo_round_scheme_base;
extern object __glo_exact_scheme_base;
extern object __glo_inexact_scheme_base;
extern object __glo_eof_91object_scheme_base;
extern object __glo_syntax_91error_scheme_base;
extern object __glo_bytevector_91copy_scheme_base;
extern object __glo_bytevector_91copy_67_scheme_base;
extern object __glo_utf8_91_125string_scheme_base;
extern object __glo_string_91_125utf8_scheme_base;
extern object __glo_denominator_scheme_base;
extern object __glo_numerator_scheme_base;
extern object __glo_parameterize_scheme_base;
extern object __glo_peek_91u8_scheme_base;
extern object __glo_read_91u8_scheme_base;
extern object __glo_write_91u8_scheme_base;
extern object __glo_read_scheme_read;
extern object __glo_read_91all_scheme_read;
extern object __glo_include_scheme_read;
extern object __glo_include_91ci_scheme_read;
extern object __glo_display_scheme_write;
extern object __glo_write_scheme_write;
extern object __glo_write_91shared_scheme_write;
extern object __glo_write_91simple_scheme_write;
extern object __glo_current_91second_scheme_time;
extern object __glo_current_91jiffy_scheme_time;
extern object __glo_jiffies_91per_91second_scheme_time;
extern object __glo_string_123_127_191_191inline_191_191_scheme_base;
extern object __glo_string_121_127_191_191inline_191_191_scheme_base;
extern object __glo_string_121_123_127_191_191inline_191_191_scheme_base;
extern object __glo_string_125_127_191_191inline_191_191_scheme_base;
extern object __glo_string_125_123_127_191_191inline_191_191_scheme_base;
extern object __glo_not_191_191inline_191_191_scheme_base;
extern object __glo_zero_127_191_191inline_191_191_scheme_base;
extern object __glo_positive_127_191_191inline_191_191_scheme_base;
extern object __glo_negative_127_191_191inline_191_191_scheme_base;
extern object __glo_floor_191_191inline_191_191_scheme_base;
extern object __glo_ceiling_191_191inline_191_191_scheme_base;
extern object __glo_truncate_191_191inline_191_191_scheme_base;
extern object __glo_round_191_191inline_191_191_scheme_base;
extern object __glo_inexact_191_191inline_191_191_scheme_base;
extern object __glo_sqrt_191_191inline_191_191_scheme_base;
extern object __glo_exact_91integer_127_191_191inline_191_191_scheme_base;
extern object __glo_exact_127_191_191inline_191_191_scheme_base;
extern object __glo_complex_127_191_191inline_191_191_scheme_base;
extern object __glo_denominator_191_191inline_191_191_scheme_base;
extern object __glo_numerator_191_191inline_191_191_scheme_base;
extern object __glo_quotient_191_191inline_191_191_scheme_base;
extern object __glo_square_191_191inline_191_191_scheme_base;
extern object __glo_eof_91object_191_191inline_191_191_scheme_base;
extern object __glo_Cyc_91opaque_91eq_127_191_191inline_191_191_scheme_read;
extern object __glo_Cyc_91opaque_91unsafe_91eq_127_191_191inline_191_191_scheme_read;
extern object __glo_Cyc_91opaque_91unsafe_91string_127_191_191inline_191_191_scheme_read;
#include "cyclone/runtime.h"
#include "cyclone/runtime-main.h"
static void __lambda_65(void *data, int argc, closure _,object k_73240) ;
static void __lambda_66(void *data, int argc, object self_73306, object r_73241) ;
static void __lambda_23(void *data, int argc, closure _,object k_73188, object name_7347_73116, object count_7348_73117, object thunk_7349_73118, object ok_127_7350_73119) ;
static void __lambda_24(void *data, int argc, object self_73263, object rounded_73121) ;
static void __lambda_70(void *data, int argc, object self_73264, object rounded_73121) ;
static void __lambda_64(void *data, int argc, object self_73265, object k_73235, object x_7351_73123) ;
static void __lambda_25(void *data, int argc, object self_73266, object r_73189) ;
static void __lambda_26(void *data, int argc, object self_73267, object r_73190) ;
static void __lambda_27(void *data, int argc, object self_73268, object r_73191) ;
static void __lambda_28(void *data, int argc, object self_73269, object r_73192) ;
static void __lambda_29(void *data, int argc, object self_73270, object r_73233) ;
static void __lambda_30(void *data, int argc, object self_73271, object r_73193) ;
static void __lambda_31(void *data, int argc, object self_73272, object j_95s_7354_73124) ;
static void __lambda_32(void *data, int argc, object self_73273, object t0_7357_73125) ;
static void __lambda_33(void *data, int argc, object self_73274, object j0_7360_73126) ;
static void __lambda_34(void *data, int argc, object self_73275, object loop_7365_73129) ;
static void __lambda_69(void *data, int argc, object self_73276, object loop_7365_73129) ;
static void __lambda_36(void *data, int argc, object self_73277, object k_73199, object i_7366_73130, object result_7367_73131) ;
static void __lambda_38(void *data, int argc, object self_73279, object r_73203) ;
static void __lambda_59(void *data, int argc, object self_73300, object r_73228) ;
static void __lambda_60(void *data, int argc, object self_73301, object r_73229) ;
static void __lambda_61(void *data, int argc, object self_73302, object r_73230) ;
static void __lambda_62(void *data, int argc, object self_73303, object r_73232) ;
static void __lambda_63(void *data, int argc, object self_73304, object r_73231) ;
static void __lambda_39(void *data, int argc, object self_73280, object j1_7376_73132) ;
static void __lambda_40(void *data, int argc, object self_73281, object t1_7379_73133) ;
static void __lambda_41(void *data, int argc, object self_73282, object secs2_7388_73136) ;
static void __lambda_42(void *data, int argc, object self_73283, object r_73210) ;
static void __lambda_43(void *data, int argc, object self_73284, object r_73211) ;
static void __lambda_44(void *data, int argc, object self_73285, object r_73212) ;
static void __lambda_45(void *data, int argc, object self_73286, object r_73213) ;
static void __lambda_46(void *data, int argc, object self_73287, object r_73214) ;
static void __lambda_47(void *data, int argc, object self_73288, object r_73215) ;
static void __lambda_48(void *data, int argc, object self_73289, object r_73216) ;
static void __lambda_49(void *data, int argc, object self_73290, object r_73217) ;
static void __lambda_50(void *data, int argc, object self_73291, object r_73225) ;
static void __lambda_51(void *data, int argc, object self_73292, object r_73218) ;
static void __lambda_52(void *data, int argc, object self_73293, object r_73219) ;
static void __lambda_53(void *data, int argc, object self_73294, object r_73220) ;
static void __lambda_54(void *data, int argc, object self_73295, object r_73221) ;
static void __lambda_55(void *data, int argc, object self_73296, object r_73222) ;
static void __lambda_56(void *data, int argc, object self_73297, object r_73223) ;
static void __lambda_57(void *data, int argc, object self_73298, object r_73224) ;
static void __lambda_58(void *data, int argc, object self_73299, object r_73204) ;
static void __lambda_37(void *data, int argc, object self_73278, object r_73202) ;
static void __lambda_35(void *data, int argc, object self_73305, object r_73197) ;
static void __lambda_16(void *data, int argc, closure _,object k_73174, object r_7342_73111, object x_7343_73112) ;
static void __lambda_22(void *data, int argc, object self_73262, object k_73177, object v_7345_73114, object i_7346_73115) ;
static void __lambda_17(void *data, int argc, object self_73257, object k_73179) ;
static void __lambda_21(void *data, int argc, object self_73261, object k_73185, object x_7344_73113) ;
static void __lambda_18(void *data, int argc, object self_73258, object r_73180) ;
static void __lambda_20(void *data, int argc, object self_73259, object r_73181) ;
static void __lambda_19(void *data, int argc, object self_73260, object k_73182) ;
static void __lambda_11(void *data, int argc, closure _,object k_73161) ;
static void __lambda_12(void *data, int argc, object self_73253, object r_73171) ;
static void __lambda_13(void *data, int argc, object self_73254, object ll_7336_73108) ;
static void __lambda_15(void *data, int argc, object self_73256, object k_73168, object result_7341_73110) ;
static void __lambda_14(void *data, int argc, object self_73255, object k_73170) ;
static void __lambda_6(void *data, int argc, closure _,object k_73150, object l_7310_7397) ;
static void __lambda_7(void *data, int argc, object self_73248, object l_7314_7398, object a_7315_7399) ;
static void __lambda_8(void *data, int argc, object self_73249, object lp_7311_7316_73100) ;
static void __lambda_68(void *data, int argc, object self_73250, object lp_7311_7316_73100) ;
static void __lambda_10(void *data, int argc, object self_73251, object k_73154, object l_7317_73101, object a_7318_73102) ;
static void __lambda_9(void *data, int argc, object self_73252, object r_73152) ;
static void __lambda_1(void *data, int argc, closure _,object k_73139, object n_731_7391) ;
static void __lambda_2(void *data, int argc, object self_73243, object n_735_7392, object a_736_7393) ;
static void __lambda_3(void *data, int argc, object self_73244, object lp_732_737_7394) ;
static void __lambda_67(void *data, int argc, object self_73245, object lp_732_737_7394) ;
static void __lambda_5(void *data, int argc, object self_73246, object k_73143, object n_738_7395, object a_739_7396) ;
static void __lambda_4(void *data, int argc, object self_73247, object r_73141) ;

static void __lambda_65(void *data, int argc, closure _,object k_73240) {
  Cyc_st_add(data, "diviter.scm:this-scheme-implementation-name");

closureN_type c_73609;
c_73609.hdr.mark = gc_color_red;
 c_73609.hdr.grayed = 0;
c_73609.tag = closureN_tag;
 c_73609.fn = (function_type)__lambda_66;
c_73609.num_args = 1;
c_73609.num_elements = 1;
c_73609.elements = (object *)alloca(sizeof(object) * 1);
c_73609.elements[0] = k_73240;

return_closcall1(data,  __glo_Cyc_91version_scheme_base,  &c_73609);; 
}

static void __lambda_66(void *data, int argc, object self_73306, object r_73241) {
  
make_utf8_string_with_len(c_73615, "cyclone-", 8, 8);

object c_73614 = Cyc_string_append(data,  ((closureN)self_73306)->elements[0],2,&c_73615, r_73241);
return_closcall1(data,  ((closureN)self_73306)->elements[0],  c_73614);; 
}

static void __lambda_23(void *data, int argc, closure _,object k_73188, object name_7347_73116, object count_7348_73117, object thunk_7349_73118, object ok_127_7350_73119) {
  Cyc_st_add(data, "diviter.scm:run-r7rs-benchmark");

closureN_type c_73423;
c_73423.hdr.mark = gc_color_red;
 c_73423.hdr.grayed = 0;
c_73423.tag = closureN_tag;
 c_73423.fn = (function_type)__lambda_24;
c_73423.num_args = 1;
c_73423.num_elements = 5;
c_73423.elements = (object *)alloca(sizeof(object) * 5);
c_73423.elements[0] = count_7348_73117;
c_73423.elements[1] = k_73188;
c_73423.elements[2] = name_7347_73116;
c_73423.elements[3] = ok_127_7350_73119;
c_73423.elements[4] = thunk_7349_73118;

return_direct_with_clo1(data,(closure)&c_73423,__lambda_24,  boolean_f);; 
}

static void __lambda_24(void *data, int argc, object self_73263, object rounded_73121) {
  
closureN_type c_73425;
c_73425.hdr.mark = gc_color_red;
 c_73425.hdr.grayed = 0;
c_73425.tag = closureN_tag;
 c_73425.fn = (function_type)__lambda_70;
c_73425.num_args = 1;
c_73425.num_elements = 5;
c_73425.elements = (object *)alloca(sizeof(object) * 5);
c_73425.elements[0] = ((closureN)self_73263)->elements[0];
c_73425.elements[1] = ((closureN)self_73263)->elements[1];
c_73425.elements[2] = ((closureN)self_73263)->elements[2];
c_73425.elements[3] = ((closureN)self_73263)->elements[3];
c_73425.elements[4] = ((closureN)self_73263)->elements[4];


make_cell(c_73606,rounded_73121);
return_direct_with_clo1(data,(closure)&c_73425,__lambda_70,  &c_73606);; 
}

static void __lambda_70(void *data, int argc, object self_73264, object rounded_73121) {
  
closureN_type c_73427;
c_73427.hdr.mark = gc_color_red;
 c_73427.hdr.grayed = 0;
c_73427.tag = closureN_tag;
 c_73427.fn = (function_type)__lambda_25;
c_73427.num_args = 1;
c_73427.num_elements = 6;
c_73427.elements = (object *)alloca(sizeof(object) * 6);
c_73427.elements[0] = ((closureN)self_73264)->elements[0];
c_73427.elements[1] = ((closureN)self_73264)->elements[1];
c_73427.elements[2] = ((closureN)self_73264)->elements[2];
c_73427.elements[3] = ((closureN)self_73264)->elements[3];
c_73427.elements[4] = rounded_73121;
c_73427.elements[5] = ((closureN)self_73264)->elements[4];


mclosure0(c_73590, (function_type)__lambda_64);c_73590.num_args = 1;
return_direct_with_clo1(data,(closure)&c_73427,__lambda_25,  Cyc_set_cell(data, rounded_73121, &c_73590));; 
}

static void __lambda_64(void *data, int argc, object self_73265, object k_73235, object x_7351_73123) {
  
complex_num_type local_73602; object c_73603 = Cyc_fast_mul(data,&local_73602,obj_int2obj(1000), x_7351_73123);

complex_num_type local_73598; object c_73599 = ((inline_function_type)
                   ((closure)__glo_round_191_191inline_191_191_scheme_base)->fn)(data,&local_73598,c_73603);

complex_num_type local_73594; object c_73595 = Cyc_fast_div(data,&local_73594,c_73599, obj_int2obj(1000));
return_closcall1(data,  k_73235,  c_73595);; 
}

static void __lambda_25(void *data, int argc, object self_73266, object r_73189) {
  
closureN_type c_73429;
c_73429.hdr.mark = gc_color_red;
 c_73429.hdr.grayed = 0;
c_73429.tag = closureN_tag;
 c_73429.fn = (function_type)__lambda_26;
c_73429.num_args = 1;
c_73429.num_elements = 6;
c_73429.elements = (object *)alloca(sizeof(object) * 6);
c_73429.elements[0] = ((closureN)self_73266)->elements[0];
c_73429.elements[1] = ((closureN)self_73266)->elements[1];
c_73429.elements[2] = ((closureN)self_73266)->elements[2];
c_73429.elements[3] = ((closureN)self_73266)->elements[3];
c_73429.elements[4] = ((closureN)self_73266)->elements[4];
c_73429.elements[5] = ((closureN)self_73266)->elements[5];


make_utf8_string_with_len(c_73587, "Running ", 8, 8);
return_closcall2(data,  __glo_display_scheme_write,  &c_73429, &c_73587);; 
}

static void __lambda_26(void *data, int argc, object self_73267, object r_73190) {
  
closureN_type c_73431;
c_73431.hdr.mark = gc_color_red;
 c_73431.hdr.grayed = 0;
c_73431.tag = closureN_tag;
 c_73431.fn = (function_type)__lambda_27;
c_73431.num_args = 1;
c_73431.num_elements = 6;
c_73431.elements = (object *)alloca(sizeof(object) * 6);
c_73431.elements[0] = ((closureN)self_73267)->elements[0];
c_73431.elements[1] = ((closureN)self_73267)->elements[1];
c_73431.elements[2] = ((closureN)self_73267)->elements[2];
c_73431.elements[3] = ((closureN)self_73267)->elements[3];
c_73431.elements[4] = ((closureN)self_73267)->elements[4];
c_73431.elements[5] = ((closureN)self_73267)->elements[5];

return_closcall2(data,  __glo_display_scheme_write,  &c_73431, ((closureN)self_73267)->elements[2]);; 
}

static void __lambda_27(void *data, int argc, object self_73268, object r_73191) {
  
closureN_type c_73433;
c_73433.hdr.mark = gc_color_red;
 c_73433.hdr.grayed = 0;
c_73433.tag = closureN_tag;
 c_73433.fn = (function_type)__lambda_28;
c_73433.num_args = 1;
c_73433.num_elements = 6;
c_73433.elements = (object *)alloca(sizeof(object) * 6);
c_73433.elements[0] = ((closureN)self_73268)->elements[0];
c_73433.elements[1] = ((closureN)self_73268)->elements[1];
c_73433.elements[2] = ((closureN)self_73268)->elements[2];
c_73433.elements[3] = ((closureN)self_73268)->elements[3];
c_73433.elements[4] = ((closureN)self_73268)->elements[4];
c_73433.elements[5] = ((closureN)self_73268)->elements[5];

return_closcall1(data,  __glo_newline_scheme_base,  &c_73433);; 
}

static void __lambda_28(void *data, int argc, object self_73269, object r_73192) {
  
closureN_type c_73435;
c_73435.hdr.mark = gc_color_red;
 c_73435.hdr.grayed = 0;
c_73435.tag = closureN_tag;
 c_73435.fn = (function_type)__lambda_29;
c_73435.num_args = 1;
c_73435.num_elements = 6;
c_73435.elements = (object *)alloca(sizeof(object) * 6);
c_73435.elements[0] = ((closureN)self_73269)->elements[0];
c_73435.elements[1] = ((closureN)self_73269)->elements[1];
c_73435.elements[2] = ((closureN)self_73269)->elements[2];
c_73435.elements[3] = ((closureN)self_73269)->elements[3];
c_73435.elements[4] = ((closureN)self_73269)->elements[4];
c_73435.elements[5] = ((closureN)self_73269)->elements[5];

return_closcall1(data,  __glo_current_91output_91port_scheme_base,  &c_73435);; 
}

static void __lambda_29(void *data, int argc, object self_73270, object r_73233) {
  
closureN_type c_73437;
c_73437.hdr.mark = gc_color_red;
 c_73437.hdr.grayed = 0;
c_73437.tag = closureN_tag;
 c_73437.fn = (function_type)__lambda_30;
c_73437.num_args = 1;
c_73437.num_elements = 6;
c_73437.elements = (object *)alloca(sizeof(object) * 6);
c_73437.elements[0] = ((closureN)self_73270)->elements[0];
c_73437.elements[1] = ((closureN)self_73270)->elements[1];
c_73437.elements[2] = ((closureN)self_73270)->elements[2];
c_73437.elements[3] = ((closureN)self_73270)->elements[3];
c_73437.elements[4] = ((closureN)self_73270)->elements[4];
c_73437.elements[5] = ((closureN)self_73270)->elements[5];

return_closcall2(data,  __glo_flush_91output_91port_scheme_base,  &c_73437, r_73233);; 
}

static void __lambda_30(void *data, int argc, object self_73271, object r_73193) {
  
closureN_type c_73439;
c_73439.hdr.mark = gc_color_red;
 c_73439.hdr.grayed = 0;
c_73439.tag = closureN_tag;
 c_73439.fn = (function_type)__lambda_31;
c_73439.num_args = 1;
c_73439.num_elements = 6;
c_73439.elements = (object *)alloca(sizeof(object) * 6);
c_73439.elements[0] = ((closureN)self_73271)->elements[0];
c_73439.elements[1] = ((closureN)self_73271)->elements[1];
c_73439.elements[2] = ((closureN)self_73271)->elements[2];
c_73439.elements[3] = ((closureN)self_73271)->elements[3];
c_73439.elements[4] = ((closureN)self_73271)->elements[4];
c_73439.elements[5] = ((closureN)self_73271)->elements[5];

return_closcall1(data,  __glo_jiffies_91per_91second_scheme_time,  &c_73439);; 
}

static void __lambda_31(void *data, int argc, object self_73272, object j_95s_7354_73124) {
  
closureN_type c_73441;
c_73441.hdr.mark = gc_color_red;
 c_73441.hdr.grayed = 0;
c_73441.tag = closureN_tag;
 c_73441.fn = (function_type)__lambda_32;
c_73441.num_args = 1;
c_73441.num_elements = 7;
c_73441.elements = (object *)alloca(sizeof(object) * 7);
c_73441.elements[0] = ((closureN)self_73272)->elements[0];
c_73441.elements[1] = j_95s_7354_73124;
c_73441.elements[2] = ((closureN)self_73272)->elements[1];
c_73441.elements[3] = ((closureN)self_73272)->elements[2];
c_73441.elements[4] = ((closureN)self_73272)->elements[3];
c_73441.elements[5] = ((closureN)self_73272)->elements[4];
c_73441.elements[6] = ((closureN)self_73272)->elements[5];

return_closcall1(data,  __glo_current_91second_scheme_time,  &c_73441);; 
}

static void __lambda_32(void *data, int argc, object self_73273, object t0_7357_73125) {
  
closureN_type c_73443;
c_73443.hdr.mark = gc_color_red;
 c_73443.hdr.grayed = 0;
c_73443.tag = closureN_tag;
 c_73443.fn = (function_type)__lambda_33;
c_73443.num_args = 1;
c_73443.num_elements = 8;
c_73443.elements = (object *)alloca(sizeof(object) * 8);
c_73443.elements[0] = ((closureN)self_73273)->elements[0];
c_73443.elements[1] = ((closureN)self_73273)->elements[1];
c_73443.elements[2] = ((closureN)self_73273)->elements[2];
c_73443.elements[3] = ((closureN)self_73273)->elements[3];
c_73443.elements[4] = ((closureN)self_73273)->elements[4];
c_73443.elements[5] = ((closureN)self_73273)->elements[5];
c_73443.elements[6] = t0_7357_73125;
c_73443.elements[7] = ((closureN)self_73273)->elements[6];

return_closcall1(data,  __glo_current_91jiffy_scheme_time,  &c_73443);; 
}

static void __lambda_33(void *data, int argc, object self_73274, object j0_7360_73126) {
  
closureN_type c_73445;
c_73445.hdr.mark = gc_color_red;
 c_73445.hdr.grayed = 0;
c_73445.tag = closureN_tag;
 c_73445.fn = (function_type)__lambda_34;
c_73445.num_args = 1;
c_73445.num_elements = 9;
c_73445.elements = (object *)alloca(sizeof(object) * 9);
c_73445.elements[0] = ((closureN)self_73274)->elements[0];
c_73445.elements[1] = ((closureN)self_73274)->elements[1];
c_73445.elements[2] = j0_7360_73126;
c_73445.elements[3] = ((closureN)self_73274)->elements[2];
c_73445.elements[4] = ((closureN)self_73274)->elements[3];
c_73445.elements[5] = ((closureN)self_73274)->elements[4];
c_73445.elements[6] = ((closureN)self_73274)->elements[5];
c_73445.elements[7] = ((closureN)self_73274)->elements[6];
c_73445.elements[8] = ((closureN)self_73274)->elements[7];

return_direct_with_clo1(data,(closure)&c_73445,__lambda_34,  boolean_f);; 
}

static void __lambda_34(void *data, int argc, object self_73275, object loop_7365_73129) {
  
closureN_type c_73447;
c_73447.hdr.mark = gc_color_red;
 c_73447.hdr.grayed = 0;
c_73447.tag = closureN_tag;
 c_73447.fn = (function_type)__lambda_69;
c_73447.num_args = 1;
c_73447.num_elements = 9;
c_73447.elements = (object *)alloca(sizeof(object) * 9);
c_73447.elements[0] = ((closureN)self_73275)->elements[0];
c_73447.elements[1] = ((closureN)self_73275)->elements[1];
c_73447.elements[2] = ((closureN)self_73275)->elements[2];
c_73447.elements[3] = ((closureN)self_73275)->elements[3];
c_73447.elements[4] = ((closureN)self_73275)->elements[4];
c_73447.elements[5] = ((closureN)self_73275)->elements[5];
c_73447.elements[6] = ((closureN)self_73275)->elements[6];
c_73447.elements[7] = ((closureN)self_73275)->elements[7];
c_73447.elements[8] = ((closureN)self_73275)->elements[8];


make_cell(c_73585,loop_7365_73129);
return_direct_with_clo1(data,(closure)&c_73447,__lambda_69,  &c_73585);; 
}

static void __lambda_69(void *data, int argc, object self_73276, object loop_7365_73129) {
  
closureN_type c_73449;
c_73449.hdr.mark = gc_color_red;
 c_73449.hdr.grayed = 0;
c_73449.tag = closureN_tag;
 c_73449.fn = (function_type)__lambda_35;
c_73449.num_args = 1;
c_73449.num_elements = 2;
c_73449.elements = (object *)alloca(sizeof(object) * 2);
c_73449.elements[0] = ((closureN)self_73276)->elements[3];
c_73449.elements[1] = loop_7365_73129;


closureN_type c_73457;
c_73457.hdr.mark = gc_color_red;
 c_73457.hdr.grayed = 0;
c_73457.tag = closureN_tag;
 c_73457.fn = (function_type)__lambda_36;
c_73457.num_args = 2;
c_73457.num_elements = 9;
c_73457.elements = (object *)alloca(sizeof(object) * 9);
c_73457.elements[0] = ((closureN)self_73276)->elements[0];
c_73457.elements[1] = ((closureN)self_73276)->elements[1];
c_73457.elements[2] = ((closureN)self_73276)->elements[2];
c_73457.elements[3] = loop_7365_73129;
c_73457.elements[4] = ((closureN)self_73276)->elements[4];
c_73457.elements[5] = ((closureN)self_73276)->elements[5];
c_73457.elements[6] = ((closureN)self_73276)->elements[6];
c_73457.elements[7] = ((closureN)self_73276)->elements[7];
c_73457.elements[8] = ((closureN)self_73276)->elements[8];

return_direct_with_clo1(data,(closure)&c_73449,__lambda_35,  Cyc_set_cell(data, loop_7365_73129, &c_73457));; 
}

static void __lambda_36(void *data, int argc, object self_73277, object k_73199, object i_7366_73130, object result_7367_73131) {
    object c_73460 = Cyc_num_fast_lt_op(data,i_7366_73130, ((closureN)self_73277)->elements[0]);
if( (boolean_f != c_73460) ){ 
  
closureN_type c_73464;
c_73464.hdr.mark = gc_color_red;
 c_73464.hdr.grayed = 0;
c_73464.tag = closureN_tag;
 c_73464.fn = (function_type)__lambda_37;
c_73464.num_args = 1;
c_73464.num_elements = 3;
c_73464.elements = (object *)alloca(sizeof(object) * 3);
c_73464.elements[0] = i_7366_73130;
c_73464.elements[1] = k_73199;
c_73464.elements[2] = ((closureN)self_73277)->elements[3];

return_closcall1(data,  ((closureN)self_73277)->elements[8],  &c_73464);
} else { 
  
closureN_type c_73477;
c_73477.hdr.mark = gc_color_red;
 c_73477.hdr.grayed = 0;
c_73477.tag = closureN_tag;
 c_73477.fn = (function_type)__lambda_38;
c_73477.num_args = 1;
c_73477.num_elements = 7;
c_73477.elements = (object *)alloca(sizeof(object) * 7);
c_73477.elements[0] = ((closureN)self_73277)->elements[1];
c_73477.elements[1] = ((closureN)self_73277)->elements[2];
c_73477.elements[2] = k_73199;
c_73477.elements[3] = ((closureN)self_73277)->elements[4];
c_73477.elements[4] = result_7367_73131;
c_73477.elements[5] = ((closureN)self_73277)->elements[6];
c_73477.elements[6] = ((closureN)self_73277)->elements[7];

return_closcall2(data,  ((closureN)self_73277)->elements[5],  &c_73477, result_7367_73131);}
; 
}

static void __lambda_38(void *data, int argc, object self_73279, object r_73203) {
  if( (boolean_f != r_73203) ){ 
  
closureN_type c_73479;
c_73479.hdr.mark = gc_color_red;
 c_73479.hdr.grayed = 0;
c_73479.tag = closureN_tag;
 c_73479.fn = (function_type)__lambda_39;
c_73479.num_args = 1;
c_73479.num_elements = 7;
c_73479.elements = (object *)alloca(sizeof(object) * 7);
c_73479.elements[0] = ((closureN)self_73279)->elements[0];
c_73479.elements[1] = ((closureN)self_73279)->elements[1];
c_73479.elements[2] = ((closureN)self_73279)->elements[2];
c_73479.elements[3] = ((closureN)self_73279)->elements[3];
c_73479.elements[4] = ((closureN)self_73279)->elements[4];
c_73479.elements[5] = ((closureN)self_73279)->elements[5];
c_73479.elements[6] = ((closureN)self_73279)->elements[6];

return_closcall1(data,  __glo_current_91jiffy_scheme_time,  &c_73479);
} else { 
  
closureN_type c_73569;
c_73569.hdr.mark = gc_color_red;
 c_73569.hdr.grayed = 0;
c_73569.tag = closureN_tag;
 c_73569.fn = (function_type)__lambda_59;
c_73569.num_args = 1;
c_73569.num_elements = 2;
c_73569.elements = (object *)alloca(sizeof(object) * 2);
c_73569.elements[0] = ((closureN)self_73279)->elements[2];
c_73569.elements[1] = ((closureN)self_73279)->elements[4];


make_utf8_string_with_len(c_73582, "ERROR: returned incorrect result: ", 34, 34);
return_closcall2(data,  __glo_display_scheme_write,  &c_73569, &c_73582);}
; 
}

static void __lambda_59(void *data, int argc, object self_73300, object r_73228) {
  
closureN_type c_73571;
c_73571.hdr.mark = gc_color_red;
 c_73571.hdr.grayed = 0;
c_73571.tag = closureN_tag;
 c_73571.fn = (function_type)__lambda_60;
c_73571.num_args = 1;
c_73571.num_elements = 2;
c_73571.elements = (object *)alloca(sizeof(object) * 2);
c_73571.elements[0] = ((closureN)self_73300)->elements[0];
c_73571.elements[1] = ((closureN)self_73300)->elements[1];

return_closcall2(data,  __glo_write_scheme_write,  &c_73571, ((closureN)self_73300)->elements[1]);; 
}

static void __lambda_60(void *data, int argc, object self_73301, object r_73229) {
  
closureN_type c_73573;
c_73573.hdr.mark = gc_color_red;
 c_73573.hdr.grayed = 0;
c_73573.tag = closureN_tag;
 c_73573.fn = (function_type)__lambda_61;
c_73573.num_args = 1;
c_73573.num_elements = 2;
c_73573.elements = (object *)alloca(sizeof(object) * 2);
c_73573.elements[0] = ((closureN)self_73301)->elements[0];
c_73573.elements[1] = ((closureN)self_73301)->elements[1];

return_closcall1(data,  __glo_newline_scheme_base,  &c_73573);; 
}

static void __lambda_61(void *data, int argc, object self_73302, object r_73230) {
  
closureN_type c_73575;
c_73575.hdr.mark = gc_color_red;
 c_73575.hdr.grayed = 0;
c_73575.tag = closureN_tag;
 c_73575.fn = (function_type)__lambda_62;
c_73575.num_args = 1;
c_73575.num_elements = 2;
c_73575.elements = (object *)alloca(sizeof(object) * 2);
c_73575.elements[0] = ((closureN)self_73302)->elements[0];
c_73575.elements[1] = ((closureN)self_73302)->elements[1];

return_closcall1(data,  __glo_current_91output_91port_scheme_base,  &c_73575);; 
}

static void __lambda_62(void *data, int argc, object self_73303, object r_73232) {
  
closureN_type c_73577;
c_73577.hdr.mark = gc_color_red;
 c_73577.hdr.grayed = 0;
c_73577.tag = closureN_tag;
 c_73577.fn = (function_type)__lambda_63;
c_73577.num_args = 1;
c_73577.num_elements = 2;
c_73577.elements = (object *)alloca(sizeof(object) * 2);
c_73577.elements[0] = ((closureN)self_73303)->elements[0];
c_73577.elements[1] = ((closureN)self_73303)->elements[1];

return_closcall2(data,  __glo_flush_91output_91port_scheme_base,  &c_73577, r_73232);; 
}

static void __lambda_63(void *data, int argc, object self_73304, object r_73231) {
  return_closcall1(data,  ((closureN)self_73304)->elements[0],  ((closureN)self_73304)->elements[1]);; 
}

static void __lambda_39(void *data, int argc, object self_73280, object j1_7376_73132) {
  
closureN_type c_73481;
c_73481.hdr.mark = gc_color_red;
 c_73481.hdr.grayed = 0;
c_73481.tag = closureN_tag;
 c_73481.fn = (function_type)__lambda_40;
c_73481.num_args = 1;
c_73481.num_elements = 8;
c_73481.elements = (object *)alloca(sizeof(object) * 8);
c_73481.elements[0] = ((closureN)self_73280)->elements[0];
c_73481.elements[1] = ((closureN)self_73280)->elements[1];
c_73481.elements[2] = j1_7376_73132;
c_73481.elements[3] = ((closureN)self_73280)->elements[2];
c_73481.elements[4] = ((closureN)self_73280)->elements[3];
c_73481.elements[5] = ((closureN)self_73280)->elements[4];
c_73481.elements[6] = ((closureN)self_73280)->elements[5];
c_73481.elements[7] = ((closureN)self_73280)->elements[6];

return_closcall1(data,  __glo_current_91second_scheme_time,  &c_73481);; 
}

static void __lambda_40(void *data, int argc, object self_73281, object t1_7379_73133) {
  
closureN_type c_73486;
c_73486.hdr.mark = gc_color_red;
 c_73486.hdr.grayed = 0;
c_73486.tag = closureN_tag;
 c_73486.fn = (function_type)__lambda_41;
c_73486.num_args = 1;
c_73486.num_elements = 6;
c_73486.elements = (object *)alloca(sizeof(object) * 6);
c_73486.elements[0] = ((closureN)self_73281)->elements[0];
c_73486.elements[1] = ((closureN)self_73281)->elements[1];
c_73486.elements[2] = ((closureN)self_73281)->elements[2];
c_73486.elements[3] = ((closureN)self_73281)->elements[3];
c_73486.elements[4] = ((closureN)self_73281)->elements[4];
c_73486.elements[5] = ((closureN)self_73281)->elements[5];


complex_num_type local_73565; object c_73566 = Cyc_fast_sub(data,&local_73565,t1_7379_73133, ((closureN)self_73281)->elements[7]);
return_closcall2(data,  car(((closureN)self_73281)->elements[6]),  &c_73486, c_73566);; 
}

static void __lambda_41(void *data, int argc, object self_73282, object secs2_7388_73136) {
  
closureN_type c_73488;
c_73488.hdr.mark = gc_color_red;
 c_73488.hdr.grayed = 0;
c_73488.tag = closureN_tag;
 c_73488.fn = (function_type)__lambda_42;
c_73488.num_args = 1;
c_73488.num_elements = 7;
c_73488.elements = (object *)alloca(sizeof(object) * 7);
c_73488.elements[0] = ((closureN)self_73282)->elements[0];
c_73488.elements[1] = ((closureN)self_73282)->elements[1];
c_73488.elements[2] = ((closureN)self_73282)->elements[2];
c_73488.elements[3] = ((closureN)self_73282)->elements[3];
c_73488.elements[4] = ((closureN)self_73282)->elements[4];
c_73488.elements[5] = ((closureN)self_73282)->elements[5];
c_73488.elements[6] = secs2_7388_73136;


make_utf8_string_with_len(c_73562, "Elapsed time: ", 14, 14);
return_closcall2(data,  __glo_display_scheme_write,  &c_73488, &c_73562);; 
}

static void __lambda_42(void *data, int argc, object self_73283, object r_73210) {
  
closureN_type c_73490;
c_73490.hdr.mark = gc_color_red;
 c_73490.hdr.grayed = 0;
c_73490.tag = closureN_tag;
 c_73490.fn = (function_type)__lambda_43;
c_73490.num_args = 1;
c_73490.num_elements = 7;
c_73490.elements = (object *)alloca(sizeof(object) * 7);
c_73490.elements[0] = ((closureN)self_73283)->elements[0];
c_73490.elements[1] = ((closureN)self_73283)->elements[1];
c_73490.elements[2] = ((closureN)self_73283)->elements[2];
c_73490.elements[3] = ((closureN)self_73283)->elements[3];
c_73490.elements[4] = ((closureN)self_73283)->elements[4];
c_73490.elements[5] = ((closureN)self_73283)->elements[5];
c_73490.elements[6] = ((closureN)self_73283)->elements[6];


complex_num_type local_73557; object c_73558 = Cyc_fast_sub(data,&local_73557,((closureN)self_73283)->elements[2], ((closureN)self_73283)->elements[1]);

complex_num_type local_73553; object c_73554 = Cyc_fast_div(data,&local_73553,c_73558, ((closureN)self_73283)->elements[0]);

complex_num_type local_73549; object c_73550 = ((inline_function_type)
                   ((closure)__glo_inexact_191_191inline_191_191_scheme_base)->fn)(data,&local_73549,c_73554);
return_closcall2(data,  __glo_write_scheme_write,  &c_73490, c_73550);; 
}

static void __lambda_43(void *data, int argc, object self_73284, object r_73211) {
  
closureN_type c_73492;
c_73492.hdr.mark = gc_color_red;
 c_73492.hdr.grayed = 0;
c_73492.tag = closureN_tag;
 c_73492.fn = (function_type)__lambda_44;
c_73492.num_args = 1;
c_73492.num_elements = 7;
c_73492.elements = (object *)alloca(sizeof(object) * 7);
c_73492.elements[0] = ((closureN)self_73284)->elements[0];
c_73492.elements[1] = ((closureN)self_73284)->elements[1];
c_73492.elements[2] = ((closureN)self_73284)->elements[2];
c_73492.elements[3] = ((closureN)self_73284)->elements[3];
c_73492.elements[4] = ((closureN)self_73284)->elements[4];
c_73492.elements[5] = ((closureN)self_73284)->elements[5];
c_73492.elements[6] = ((closureN)self_73284)->elements[6];


make_utf8_string_with_len(c_73546, " seconds (", 10, 10);
return_closcall2(data,  __glo_display_scheme_write,  &c_73492, &c_73546);; 
}

static void __lambda_44(void *data, int argc, object self_73285, object r_73212) {
  
closureN_type c_73494;
c_73494.hdr.mark = gc_color_red;
 c_73494.hdr.grayed = 0;
c_73494.tag = closureN_tag;
 c_73494.fn = (function_type)__lambda_45;
c_73494.num_args = 1;
c_73494.num_elements = 6;
c_73494.elements = (object *)alloca(sizeof(object) * 6);
c_73494.elements[0] = ((closureN)self_73285)->elements[0];
c_73494.elements[1] = ((closureN)self_73285)->elements[1];
c_73494.elements[2] = ((closureN)self_73285)->elements[2];
c_73494.elements[3] = ((closureN)self_73285)->elements[3];
c_73494.elements[4] = ((closureN)self_73285)->elements[4];
c_73494.elements[5] = ((closureN)self_73285)->elements[5];

return_closcall2(data,  __glo_write_scheme_write,  &c_73494, ((closureN)self_73285)->elements[6]);; 
}

static void __lambda_45(void *data, int argc, object self_73286, object r_73213) {
  
closureN_type c_73496;
c_73496.hdr.mark = gc_color_red;
 c_73496.hdr.grayed = 0;
c_73496.tag = closureN_tag;
 c_73496.fn = (function_type)__lambda_46;
c_73496.num_args = 1;
c_73496.num_elements = 6;
c_73496.elements = (object *)alloca(sizeof(object) * 6);
c_73496.elements[0] = ((closureN)self_73286)->elements[0];
c_73496.elements[1] = ((closureN)self_73286)->elements[1];
c_73496.elements[2] = ((closureN)self_73286)->elements[2];
c_73496.elements[3] = ((closureN)self_73286)->elements[3];
c_73496.elements[4] = ((closureN)self_73286)->elements[4];
c_73496.elements[5] = ((closureN)self_73286)->elements[5];


make_utf8_string_with_len(c_73544, ") for ", 6, 6);
return_closcall2(data,  __glo_display_scheme_write,  &c_73496, &c_73544);; 
}

static void __lambda_46(void *data, int argc, object self_73287, object r_73214) {
  
closureN_type c_73498;
c_73498.hdr.mark = gc_color_red;
 c_73498.hdr.grayed = 0;
c_73498.tag = closureN_tag;
 c_73498.fn = (function_type)__lambda_47;
c_73498.num_args = 1;
c_73498.num_elements = 6;
c_73498.elements = (object *)alloca(sizeof(object) * 6);
c_73498.elements[0] = ((closureN)self_73287)->elements[0];
c_73498.elements[1] = ((closureN)self_73287)->elements[1];
c_73498.elements[2] = ((closureN)self_73287)->elements[2];
c_73498.elements[3] = ((closureN)self_73287)->elements[3];
c_73498.elements[4] = ((closureN)self_73287)->elements[4];
c_73498.elements[5] = ((closureN)self_73287)->elements[5];

return_closcall2(data,  __glo_display_scheme_write,  &c_73498, ((closureN)self_73287)->elements[4]);; 
}

static void __lambda_47(void *data, int argc, object self_73288, object r_73215) {
  
closureN_type c_73500;
c_73500.hdr.mark = gc_color_red;
 c_73500.hdr.grayed = 0;
c_73500.tag = closureN_tag;
 c_73500.fn = (function_type)__lambda_48;
c_73500.num_args = 1;
c_73500.num_elements = 6;
c_73500.elements = (object *)alloca(sizeof(object) * 6);
c_73500.elements[0] = ((closureN)self_73288)->elements[0];
c_73500.elements[1] = ((closureN)self_73288)->elements[1];
c_73500.elements[2] = ((closureN)self_73288)->elements[2];
c_73500.elements[3] = ((closureN)self_73288)->elements[3];
c_73500.elements[4] = ((closureN)self_73288)->elements[4];
c_73500.elements[5] = ((closureN)self_73288)->elements[5];

return_closcall1(data,  __glo_newline_scheme_base,  &c_73500);; 
}

static void __lambda_48(void *data, int argc, object self_73289, object r_73216) {
  
closureN_type c_73502;
c_73502.hdr.mark = gc_color_red;
 c_73502.hdr.grayed = 0;
c_73502.tag = closureN_tag;
 c_73502.fn = (function_type)__lambda_49;
c_73502.num_args = 1;
c_73502.num_elements = 6;
c_73502.elements = (object *)alloca(sizeof(object) * 6);
c_73502.elements[0] = ((closureN)self_73289)->elements[0];
c_73502.elements[1] = ((closureN)self_73289)->elements[1];
c_73502.elements[2] = ((closureN)self_73289)->elements[2];
c_73502.elements[3] = ((closureN)self_73289)->elements[3];
c_73502.elements[4] = ((closureN)self_73289)->elements[4];
c_73502.elements[5] = ((closureN)self_73289)->elements[5];


make_utf8_string_with_len(c_73542, "+!CSVLINE!+", 11, 11);
return_closcall2(data,  __glo_display_scheme_write,  &c_73502, &c_73542);; 
}

static void __lambda_49(void *data, int argc, object self_73290, object r_73217) {
  
closureN_type c_73504;
c_73504.hdr.mark = gc_color_red;
 c_73504.hdr.grayed = 0;
c_73504.tag = closureN_tag;
 c_73504.fn = (function_type)__lambda_50;
c_73504.num_args = 1;
c_73504.num_elements = 6;
c_73504.elements = (object *)alloca(sizeof(object) * 6);
c_73504.elements[0] = ((closureN)self_73290)->elements[0];
c_73504.elements[1] = ((closureN)self_73290)->elements[1];
c_73504.elements[2] = ((closureN)self_73290)->elements[2];
c_73504.elements[3] = ((closureN)self_73290)->elements[3];
c_73504.elements[4] = ((closureN)self_73290)->elements[4];
c_73504.elements[5] = ((closureN)self_73290)->elements[5];

return_closcall1(data,  __glo_this_91scheme_91implementation_91name,  &c_73504);; 
}

static void __lambda_50(void *data, int argc, object self_73291, object r_73225) {
  
closureN_type c_73506;
c_73506.hdr.mark = gc_color_red;
 c_73506.hdr.grayed = 0;
c_73506.tag = closureN_tag;
 c_73506.fn = (function_type)__lambda_51;
c_73506.num_args = 1;
c_73506.num_elements = 6;
c_73506.elements = (object *)alloca(sizeof(object) * 6);
c_73506.elements[0] = ((closureN)self_73291)->elements[0];
c_73506.elements[1] = ((closureN)self_73291)->elements[1];
c_73506.elements[2] = ((closureN)self_73291)->elements[2];
c_73506.elements[3] = ((closureN)self_73291)->elements[3];
c_73506.elements[4] = ((closureN)self_73291)->elements[4];
c_73506.elements[5] = ((closureN)self_73291)->elements[5];

return_closcall2(data,  __glo_display_scheme_write,  &c_73506, r_73225);; 
}

static void __lambda_51(void *data, int argc, object self_73292, object r_73218) {
  
closureN_type c_73508;
c_73508.hdr.mark = gc_color_red;
 c_73508.hdr.grayed = 0;
c_73508.tag = closureN_tag;
 c_73508.fn = (function_type)__lambda_52;
c_73508.num_args = 1;
c_73508.num_elements = 6;
c_73508.elements = (object *)alloca(sizeof(object) * 6);
c_73508.elements[0] = ((closureN)self_73292)->elements[0];
c_73508.elements[1] = ((closureN)self_73292)->elements[1];
c_73508.elements[2] = ((closureN)self_73292)->elements[2];
c_73508.elements[3] = ((closureN)self_73292)->elements[3];
c_73508.elements[4] = ((closureN)self_73292)->elements[4];
c_73508.elements[5] = ((closureN)self_73292)->elements[5];


make_utf8_string_with_len(c_73541, ",", 1, 1);
return_closcall2(data,  __glo_display_scheme_write,  &c_73508, &c_73541);; 
}

static void __lambda_52(void *data, int argc, object self_73293, object r_73219) {
  
closureN_type c_73510;
c_73510.hdr.mark = gc_color_red;
 c_73510.hdr.grayed = 0;
c_73510.tag = closureN_tag;
 c_73510.fn = (function_type)__lambda_53;
c_73510.num_args = 1;
c_73510.num_elements = 5;
c_73510.elements = (object *)alloca(sizeof(object) * 5);
c_73510.elements[0] = ((closureN)self_73293)->elements[0];
c_73510.elements[1] = ((closureN)self_73293)->elements[1];
c_73510.elements[2] = ((closureN)self_73293)->elements[2];
c_73510.elements[3] = ((closureN)self_73293)->elements[3];
c_73510.elements[4] = ((closureN)self_73293)->elements[5];

return_closcall2(data,  __glo_display_scheme_write,  &c_73510, ((closureN)self_73293)->elements[4]);; 
}

static void __lambda_53(void *data, int argc, object self_73294, object r_73220) {
  
closureN_type c_73512;
c_73512.hdr.mark = gc_color_red;
 c_73512.hdr.grayed = 0;
c_73512.tag = closureN_tag;
 c_73512.fn = (function_type)__lambda_54;
c_73512.num_args = 1;
c_73512.num_elements = 5;
c_73512.elements = (object *)alloca(sizeof(object) * 5);
c_73512.elements[0] = ((closureN)self_73294)->elements[0];
c_73512.elements[1] = ((closureN)self_73294)->elements[1];
c_73512.elements[2] = ((closureN)self_73294)->elements[2];
c_73512.elements[3] = ((closureN)self_73294)->elements[3];
c_73512.elements[4] = ((closureN)self_73294)->elements[4];


make_utf8_string_with_len(c_73539, ",", 1, 1);
return_closcall2(data,  __glo_display_scheme_write,  &c_73512, &c_73539);; 
}

static void __lambda_54(void *data, int argc, object self_73295, object r_73221) {
  
closureN_type c_73514;
c_73514.hdr.mark = gc_color_red;
 c_73514.hdr.grayed = 0;
c_73514.tag = closureN_tag;
 c_73514.fn = (function_type)__lambda_55;
c_73514.num_args = 1;
c_73514.num_elements = 2;
c_73514.elements = (object *)alloca(sizeof(object) * 2);
c_73514.elements[0] = ((closureN)self_73295)->elements[3];
c_73514.elements[1] = ((closureN)self_73295)->elements[4];


complex_num_type local_73534; object c_73535 = Cyc_fast_sub(data,&local_73534,((closureN)self_73295)->elements[2], ((closureN)self_73295)->elements[1]);

complex_num_type local_73530; object c_73531 = Cyc_fast_div(data,&local_73530,c_73535, ((closureN)self_73295)->elements[0]);

complex_num_type local_73526; object c_73527 = ((inline_function_type)
                   ((closure)__glo_inexact_191_191inline_191_191_scheme_base)->fn)(data,&local_73526,c_73531);
return_closcall2(data,  __glo_display_scheme_write,  &c_73514, c_73527);; 
}

static void __lambda_55(void *data, int argc, object self_73296, object r_73222) {
  
closureN_type c_73516;
c_73516.hdr.mark = gc_color_red;
 c_73516.hdr.grayed = 0;
c_73516.tag = closureN_tag;
 c_73516.fn = (function_type)__lambda_56;
c_73516.num_args = 1;
c_73516.num_elements = 2;
c_73516.elements = (object *)alloca(sizeof(object) * 2);
c_73516.elements[0] = ((closureN)self_73296)->elements[0];
c_73516.elements[1] = ((closureN)self_73296)->elements[1];

return_closcall1(data,  __glo_newline_scheme_base,  &c_73516);; 
}

static void __lambda_56(void *data, int argc, object self_73297, object r_73223) {
  
closureN_type c_73518;
c_73518.hdr.mark = gc_color_red;
 c_73518.hdr.grayed = 0;
c_73518.tag = closureN_tag;
 c_73518.fn = (function_type)__lambda_57;
c_73518.num_args = 1;
c_73518.num_elements = 2;
c_73518.elements = (object *)alloca(sizeof(object) * 2);
c_73518.elements[0] = ((closureN)self_73297)->elements[0];
c_73518.elements[1] = ((closureN)self_73297)->elements[1];

return_closcall1(data,  __glo_current_91output_91port_scheme_base,  &c_73518);; 
}

static void __lambda_57(void *data, int argc, object self_73298, object r_73224) {
  
closureN_type c_73520;
c_73520.hdr.mark = gc_color_red;
 c_73520.hdr.grayed = 0;
c_73520.tag = closureN_tag;
 c_73520.fn = (function_type)__lambda_58;
c_73520.num_args = 1;
c_73520.num_elements = 2;
c_73520.elements = (object *)alloca(sizeof(object) * 2);
c_73520.elements[0] = ((closureN)self_73298)->elements[0];
c_73520.elements[1] = ((closureN)self_73298)->elements[1];

return_closcall2(data,  __glo_flush_91output_91port_scheme_base,  &c_73520, r_73224);; 
}

static void __lambda_58(void *data, int argc, object self_73299, object r_73204) {
  return_closcall1(data,  ((closureN)self_73299)->elements[0],  ((closureN)self_73299)->elements[1]);; 
}

static void __lambda_37(void *data, int argc, object self_73278, object r_73202) {
  
complex_num_type local_73472; object c_73473 = Cyc_fast_sum(data,&local_73472,((closureN)self_73278)->elements[0], obj_int2obj(1));
return_closcall3(data,  car(((closureN)self_73278)->elements[2]),  ((closureN)self_73278)->elements[1], c_73473, r_73202);; 
}

static void __lambda_35(void *data, int argc, object self_73305, object r_73197) {
  return_closcall3(data,  car(((closureN)self_73305)->elements[1]),  ((closureN)self_73305)->elements[0], obj_int2obj(0), boolean_f);; 
}

static void __lambda_16(void *data, int argc, closure _,object k_73174, object r_7342_73111, object x_7343_73112) {
  Cyc_st_add(data, "diviter.scm:hide");

closureN_type c_73399;
c_73399.hdr.mark = gc_color_red;
 c_73399.hdr.grayed = 0;
c_73399.tag = closureN_tag;
 c_73399.fn = (function_type)__lambda_17;
c_73399.num_args = 0;
c_73399.num_elements = 1;
c_73399.elements = (object *)alloca(sizeof(object) * 1);
c_73399.elements[0] = r_7342_73111;


closureN_type c_73416;
c_73416.hdr.mark = gc_color_red;
 c_73416.hdr.grayed = 0;
c_73416.tag = closureN_tag;
 c_73416.fn = (function_type)__lambda_22;
c_73416.num_args = 2;
c_73416.num_elements = 1;
c_73416.elements = (object *)alloca(sizeof(object) * 1);
c_73416.elements[0] = x_7343_73112;

return_closcall3(data,  __glo_call_91with_91values_scheme_base,  k_73174, &c_73399, &c_73416);; 
}

static void __lambda_22(void *data, int argc, object self_73262, object k_73177, object v_7345_73114, object i_7346_73115) {
  return_closcall2(data,  Cyc_vector_ref(data, v_7345_73114, i_7346_73115),  k_73177, ((closureN)self_73262)->elements[0]);; 
}

static void __lambda_17(void *data, int argc, object self_73257, object k_73179) {
  
closureN_type c_73401;
c_73401.hdr.mark = gc_color_red;
 c_73401.hdr.grayed = 0;
c_73401.tag = closureN_tag;
 c_73401.fn = (function_type)__lambda_18;
c_73401.num_args = 1;
c_73401.num_elements = 2;
c_73401.elements = (object *)alloca(sizeof(object) * 2);
c_73401.elements[0] = k_73179;
c_73401.elements[1] = ((closureN)self_73257)->elements[0];


mclosure0(c_73414, (function_type)__lambda_21);c_73414.num_args = 1;
return_closcall3(data,  __glo_vector_scheme_base,  &c_73401, __glo_values_scheme_base, &c_73414);; 
}

static void __lambda_21(void *data, int argc, object self_73261, object k_73185, object x_7344_73113) {
  return_closcall1(data,  k_73185,  x_7344_73113);; 
}

static void __lambda_18(void *data, int argc, object self_73258, object r_73180) {
  
closureN_type c_73403;
c_73403.hdr.mark = gc_color_red;
 c_73403.hdr.grayed = 0;
c_73403.tag = closureN_tag;
 c_73403.fn = (function_type)__lambda_19;
c_73403.num_args = 0;
c_73403.num_elements = 1;
c_73403.elements = (object *)alloca(sizeof(object) * 1);
c_73403.elements[0] = ((closureN)self_73258)->elements[1];


closureN_type c_73410;
c_73410.hdr.mark = gc_color_red;
 c_73410.hdr.grayed = 0;
c_73410.tag = closureN_tag;
 c_73410.fn = (function_type)__lambda_20;
c_73410.num_args = 1;
c_73410.num_elements = 2;
c_73410.elements = (object *)alloca(sizeof(object) * 2);
c_73410.elements[0] = ((closureN)self_73258)->elements[0];
c_73410.elements[1] = r_73180;

return_direct_with_clo1(data,(closure)&c_73403,__lambda_19,  &c_73410);; 
}

static void __lambda_20(void *data, int argc, object self_73259, object r_73181) {
  return_closcall3(data,  __glo_values_scheme_base,  ((closureN)self_73259)->elements[0], ((closureN)self_73259)->elements[1], r_73181);; 
}

static void __lambda_19(void *data, int argc, object self_73260, object k_73182) {
    object c_73406 = Cyc_num_fast_lt_op(data,((closureN)self_73260)->elements[0], obj_int2obj(100));
if( (boolean_f != c_73406) ){ 
  return_direct_with_clo1(data,  k_73182,__lambda_20,  obj_int2obj(0));
} else { 
  return_direct_with_clo1(data,  k_73182,__lambda_20,  obj_int2obj(1));}
; 
}

static void __lambda_11(void *data, int argc, closure _,object k_73161) {
  Cyc_st_add(data, "diviter.scm:main");

closureN_type c_73382;
c_73382.hdr.mark = gc_color_red;
 c_73382.hdr.grayed = 0;
c_73382.tag = closureN_tag;
 c_73382.fn = (function_type)__lambda_12;
c_73382.num_args = 1;
c_73382.num_elements = 1;
c_73382.elements = (object *)alloca(sizeof(object) * 1);
c_73382.elements[0] = k_73161;

return_closcall3(data,  __glo_hide,  &c_73382, obj_int2obj(1000000), obj_int2obj(1000));; 
}

static void __lambda_12(void *data, int argc, object self_73253, object r_73171) {
  
closureN_type c_73384;
c_73384.hdr.mark = gc_color_red;
 c_73384.hdr.grayed = 0;
c_73384.tag = closureN_tag;
 c_73384.fn = (function_type)__lambda_13;
c_73384.num_args = 1;
c_73384.num_elements = 1;
c_73384.elements = (object *)alloca(sizeof(object) * 1);
c_73384.elements[0] = ((closureN)self_73253)->elements[0];

return_closcall2(data,  __glo_create_91n,  &c_73384, r_73171);; 
}

static void __lambda_13(void *data, int argc, object self_73254, object ll_7336_73108) {
  
make_utf8_string_with_len(c_73387, "diviter:1000:1000000", 20, 20);

closureN_type c_73388;
c_73388.hdr.mark = gc_color_red;
 c_73388.hdr.grayed = 0;
c_73388.tag = closureN_tag;
 c_73388.fn = (function_type)__lambda_14;
c_73388.num_args = 0;
c_73388.num_elements = 1;
c_73388.elements = (object *)alloca(sizeof(object) * 1);
c_73388.elements[0] = ll_7336_73108;


mclosure0(c_73391, (function_type)__lambda_15);c_73391.num_args = 1;
return_closcall5(data,  __glo_run_91r7rs_91benchmark,  ((closureN)self_73254)->elements[0], &c_73387, obj_int2obj(1000000), &c_73388, &c_73391);; 
}

static void __lambda_15(void *data, int argc, object self_73256, object k_73168, object result_7341_73110) {
  return_closcall1(data,  k_73168,  equalp(Cyc_length(data, result_7341_73110), obj_int2obj(500)));; 
}

static void __lambda_14(void *data, int argc, object self_73255, object k_73170) {
  return_closcall2(data,  __glo_iterative_91div2,  k_73170, ((closureN)self_73255)->elements[0]);; 
}

static void __lambda_6(void *data, int argc, closure _,object k_73150, object l_7310_7397) {
  Cyc_st_add(data, "diviter.scm:iterative-div2");

closureN_type c_73346;
c_73346.hdr.mark = gc_color_red;
 c_73346.hdr.grayed = 0;
c_73346.tag = closureN_tag;
 c_73346.fn = (function_type)__lambda_7;
c_73346.num_args = 2;
c_73346.num_elements = 1;
c_73346.elements = (object *)alloca(sizeof(object) * 1);
c_73346.elements[0] = k_73150;

return_direct_with_clo2(data,(closure)&c_73346,__lambda_7,  l_7310_7397, NULL);; 
}

static void __lambda_7(void *data, int argc, object self_73248, object l_7314_7398, object a_7315_7399) {
  
closureN_type c_73348;
c_73348.hdr.mark = gc_color_red;
 c_73348.hdr.grayed = 0;
c_73348.tag = closureN_tag;
 c_73348.fn = (function_type)__lambda_8;
c_73348.num_args = 1;
c_73348.num_elements = 3;
c_73348.elements = (object *)alloca(sizeof(object) * 3);
c_73348.elements[0] = a_7315_7399;
c_73348.elements[1] = ((closureN)self_73248)->elements[0];
c_73348.elements[2] = l_7314_7398;

return_direct_with_clo1(data,(closure)&c_73348,__lambda_8,  boolean_f);; 
}

static void __lambda_8(void *data, int argc, object self_73249, object lp_7311_7316_73100) {
  
closureN_type c_73350;
c_73350.hdr.mark = gc_color_red;
 c_73350.hdr.grayed = 0;
c_73350.tag = closureN_tag;
 c_73350.fn = (function_type)__lambda_68;
c_73350.num_args = 1;
c_73350.num_elements = 3;
c_73350.elements = (object *)alloca(sizeof(object) * 3);
c_73350.elements[0] = ((closureN)self_73249)->elements[0];
c_73350.elements[1] = ((closureN)self_73249)->elements[1];
c_73350.elements[2] = ((closureN)self_73249)->elements[2];


make_cell(c_73379,lp_7311_7316_73100);
return_direct_with_clo1(data,(closure)&c_73350,__lambda_68,  &c_73379);; 
}

static void __lambda_68(void *data, int argc, object self_73250, object lp_7311_7316_73100) {
  
closureN_type c_73352;
c_73352.hdr.mark = gc_color_red;
 c_73352.hdr.grayed = 0;
c_73352.tag = closureN_tag;
 c_73352.fn = (function_type)__lambda_9;
c_73352.num_args = 1;
c_73352.num_elements = 4;
c_73352.elements = (object *)alloca(sizeof(object) * 4);
c_73352.elements[0] = ((closureN)self_73250)->elements[0];
c_73352.elements[1] = ((closureN)self_73250)->elements[1];
c_73352.elements[2] = ((closureN)self_73250)->elements[2];
c_73352.elements[3] = lp_7311_7316_73100;


closureN_type c_73362;
c_73362.hdr.mark = gc_color_red;
 c_73362.hdr.grayed = 0;
c_73362.tag = closureN_tag;
 c_73362.fn = (function_type)__lambda_10;
c_73362.num_args = 2;
c_73362.num_elements = 1;
c_73362.elements = (object *)alloca(sizeof(object) * 1);
c_73362.elements[0] = lp_7311_7316_73100;

return_direct_with_clo1(data,(closure)&c_73352,__lambda_9,  Cyc_set_cell(data, lp_7311_7316_73100, &c_73362));; 
}

static void __lambda_10(void *data, int argc, object self_73251, object k_73154, object l_7317_73101, object a_7318_73102) {
  while(1) {
  if( (boolean_f != Cyc_is_null(l_7317_73101)) ){ 
  return_closcall1(data,  k_73154,  a_7318_73102);
} else { 
  
  pair_type * c_73374 = alloca(sizeof(pair_type));
  c_73374->hdr.mark = gc_color_red; 
  c_73374->hdr.grayed = 0; 
  c_73374->tag = pair_tag; 
  c_73374->pair_car = Cyc_car(data, l_7317_73101);
  c_73374->pair_cdr = a_7318_73102;
//make_pair(c_73374,Cyc_car(data, l_7317_73101), a_7318_73102);

  if (stack_overflow(c_73374, (((gc_thread_data *)data)->stack_limit))) {
    //printf("starting GC\n");
    object buf[3]; buf[0] = k_73154; buf[1] = l_7317_73101;buf[2] = a_7318_73102;
    GC(data, self_73251, buf, argc);
  }
//return_closcall3(data,  car(((closureN)self_73251)->elements[0]),  k_73154, Cyc_cddr(data, l_7317_73101), c_73374);
  // same, no need to reassign: k_73154 = k_73154;
  l_7317_73101 = Cyc_cddr(data, l_7317_73101);
  a_7318_73102 = c_73374;
  continue;
}; 
  }
}

static void __lambda_9(void *data, int argc, object self_73252, object r_73152) {
  return_closcall3(data,  car(((closureN)self_73252)->elements[3]),  ((closureN)self_73252)->elements[1], ((closureN)self_73252)->elements[2], ((closureN)self_73252)->elements[0]);; 
}

static void __lambda_1(void *data, int argc, closure _,object k_73139, object n_731_7391) {
  Cyc_st_add(data, "diviter.scm:create-n");

closureN_type c_73309;
c_73309.hdr.mark = gc_color_red;
 c_73309.hdr.grayed = 0;
c_73309.tag = closureN_tag;
 c_73309.fn = (function_type)__lambda_2;
c_73309.num_args = 2;
c_73309.num_elements = 1;
c_73309.elements = (object *)alloca(sizeof(object) * 1);
c_73309.elements[0] = k_73139;

return_direct_with_clo2(data,(closure)&c_73309,__lambda_2,  n_731_7391, NULL);; 
}

static void __lambda_2(void *data, int argc, object self_73243, object n_735_7392, object a_736_7393) {
  
closureN_type c_73311;
c_73311.hdr.mark = gc_color_red;
 c_73311.hdr.grayed = 0;
c_73311.tag = closureN_tag;
 c_73311.fn = (function_type)__lambda_3;
c_73311.num_args = 1;
c_73311.num_elements = 3;
c_73311.elements = (object *)alloca(sizeof(object) * 3);
c_73311.elements[0] = a_736_7393;
c_73311.elements[1] = ((closureN)self_73243)->elements[0];
c_73311.elements[2] = n_735_7392;

return_direct_with_clo1(data,(closure)&c_73311,__lambda_3,  boolean_f);; 
}

static void __lambda_3(void *data, int argc, object self_73244, object lp_732_737_7394) {
  
closureN_type c_73313;
c_73313.hdr.mark = gc_color_red;
 c_73313.hdr.grayed = 0;
c_73313.tag = closureN_tag;
 c_73313.fn = (function_type)__lambda_67;
c_73313.num_args = 1;
c_73313.num_elements = 3;
c_73313.elements = (object *)alloca(sizeof(object) * 3);
c_73313.elements[0] = ((closureN)self_73244)->elements[0];
c_73313.elements[1] = ((closureN)self_73244)->elements[1];
c_73313.elements[2] = ((closureN)self_73244)->elements[2];


make_cell(c_73343,lp_732_737_7394);
return_direct_with_clo1(data,(closure)&c_73313,__lambda_67,  &c_73343);; 
}

static void __lambda_67(void *data, int argc, object self_73245, object lp_732_737_7394) {
  
closureN_type c_73315;
c_73315.hdr.mark = gc_color_red;
 c_73315.hdr.grayed = 0;
c_73315.tag = closureN_tag;
 c_73315.fn = (function_type)__lambda_4;
c_73315.num_args = 1;
c_73315.num_elements = 4;
c_73315.elements = (object *)alloca(sizeof(object) * 4);
c_73315.elements[0] = ((closureN)self_73245)->elements[0];
c_73315.elements[1] = ((closureN)self_73245)->elements[1];
c_73315.elements[2] = lp_732_737_7394;
c_73315.elements[3] = ((closureN)self_73245)->elements[2];


closureN_type c_73325;
c_73325.hdr.mark = gc_color_red;
 c_73325.hdr.grayed = 0;
c_73325.tag = closureN_tag;
 c_73325.fn = (function_type)__lambda_5;
c_73325.num_args = 2;
c_73325.num_elements = 1;
c_73325.elements = (object *)alloca(sizeof(object) * 1);
c_73325.elements[0] = lp_732_737_7394;

return_direct_with_clo1(data,(closure)&c_73315,__lambda_4,  Cyc_set_cell(data, lp_732_737_7394, &c_73325));; 
}

static void __lambda_5(void *data, int argc, object self_73246, object k_73143, object n_738_7395, object a_739_7396) {
  while(1) {
    object c_73328 = Cyc_num_fast_eq_op(data,n_738_7395, obj_int2obj(0));
if( (boolean_f != c_73328) ){ 
  return_closcall1(data,  k_73143,  a_739_7396);
} else { 
  
complex_num_type local_73336; object c_73337 = Cyc_fast_sub(data,&local_73336,n_738_7395, obj_int2obj(1));

alloca_pair(c_73340,NULL, a_739_7396);
//return_closcall3(data,  car(((closureN)self_73246)->elements[0]),  k_73143, c_73337, c_73340);}
  if (stack_overflow(c_73340, (((gc_thread_data *)data)->stack_limit))) {
    //printf("starting GC\n");
    object buf[3]; 
    buf[0] = k_73143;
    buf[1] = c_73337;
    buf[2] = c_73340;
    GC(data, self_73246, buf, argc);
  }
  // optimize out: k_73143 = k_73143;
  n_738_7395 = c_73337;
  a_739_7396 = c_73340;
  continue;
; 
}}}

static void __lambda_4(void *data, int argc, object self_73247, object r_73141) {
  return_closcall3(data,  car(((closureN)self_73247)->elements[2]),  ((closureN)self_73247)->elements[1], ((closureN)self_73247)->elements[3], ((closureN)self_73247)->elements[0]);; 
}

static void c_entry_pt_first_lambda(void *data, int argc, closure cont, object value);
extern void c_schemecyclonecommon_entry_pt(void *data, int argc, closure cont, object value);
extern void c_schemebase_entry_pt(void *data, int argc, closure cont, object value);
extern void c_schemetime_entry_pt(void *data, int argc, closure cont, object value);
extern void c_schemewrite_entry_pt(void *data, int argc, closure cont, object value);
extern void c_scheme_char_entry_pt(void *data, int argc, closure cont, object value);
extern void c_schemeread_entry_pt(void *data, int argc, closure cont, object value);
static void c_entry_pt(data, argc, env,cont) void *data; int argc; closure env,cont; { 
Cyc_set_globals_changed((gc_thread_data *)data);

  add_global((object *) &__glo_this_91scheme_91implementation_91name);
  add_global((object *) &__glo_run_91r7rs_91benchmark);
  add_global((object *) &__glo_hide);
  add_global((object *) &__glo_main);
  add_global((object *) &__glo_iterative_91div2);
  add_global((object *) &__glo_create_91n);
  mclosure0(c_73607, (function_type)__lambda_65);c_73607.num_args = 0; 
  __glo_this_91scheme_91implementation_91name = &c_73607; 
  mclosure0(c_73421, (function_type)__lambda_23);c_73421.num_args = 4; 
  __glo_run_91r7rs_91benchmark = &c_73421; 
  mclosure0(c_73397, (function_type)__lambda_16);c_73397.num_args = 2; 
  __glo_hide = &c_73397; 
  mclosure0(c_73380, (function_type)__lambda_11);c_73380.num_args = 0; 
  __glo_main = &c_73380; 
  mclosure0(c_73344, (function_type)__lambda_6);c_73344.num_args = 1; 
  __glo_iterative_91div2 = &c_73344; 
  mclosure0(c_73307, (function_type)__lambda_1);c_73307.num_args = 1; 
  __glo_create_91n = &c_73307; 

  make_cvar(cvar_73617, (object *)&__glo_this_91scheme_91implementation_91name);make_pair(pair_73618, find_or_add_symbol("this-scheme-implementation-name"), &cvar_73617);
  make_cvar(cvar_73619, (object *)&__glo_run_91r7rs_91benchmark);make_pair(pair_73620, find_or_add_symbol("run-r7rs-benchmark"), &cvar_73619);
  make_cvar(cvar_73621, (object *)&__glo_hide);make_pair(pair_73622, find_or_add_symbol("hide"), &cvar_73621);
  make_cvar(cvar_73623, (object *)&__glo_main);make_pair(pair_73624, find_or_add_symbol("main"), &cvar_73623);
  make_cvar(cvar_73625, (object *)&__glo_iterative_91div2);make_pair(pair_73626, find_or_add_symbol("iterative-div2"), &cvar_73625);
  make_cvar(cvar_73627, (object *)&__glo_create_91n);make_pair(pair_73628, find_or_add_symbol("create-n"), &cvar_73627);
make_pair(c_73634, &pair_73618,Cyc_global_variables);
make_pair(c_73633, &pair_73620, &c_73634);
make_pair(c_73632, &pair_73622, &c_73633);
make_pair(c_73631, &pair_73624, &c_73632);
make_pair(c_73630, &pair_73626, &c_73631);
make_pair(c_73629, &pair_73628, &c_73630);
Cyc_global_variables = &c_73629;
mclosure1(c_done, c_entry_pt_first_lambda, &c_done);
mclosure1(c_73635, c_schemeread_entry_pt, &c_done);
mclosure1(c_73636, c_scheme_char_entry_pt, &c_73635);
mclosure1(c_73637, c_schemewrite_entry_pt, &c_73636);
mclosure1(c_73638, c_schemetime_entry_pt, &c_73637);
mclosure1(c_73639, c_schemebase_entry_pt, &c_73638);
mclosure1(c_73640, c_schemecyclonecommon_entry_pt, &c_73639);
(c_73640.fn)(data, 0, &c_73640, &c_73640);
}
static void c_entry_pt_first_lambda(void *data, int argc, closure cont, object value) {
  
    
    
    
    
    
    return_closcall1(data,  __glo_main,  primitive__75halt);
;
}
int main(int argc, char **argv, char **envp)
{gc_thread_data *thd;
 long stack_size = global_stack_size = STACK_SIZE;
 long heap_size = global_heap_size = HEAP_SIZE;
 mclosure0(clos_halt,&Cyc_halt);  // Halt if final closure is reached
 mclosure0(entry_pt,&c_entry_pt); // First function to execute
 _cyc_argc = argc;
 _cyc_argv = argv;
 set_env_variables(envp);
 gc_initialize();
 thd = malloc(sizeof(gc_thread_data));
 gc_thread_data_init(thd, 0, (char *) &stack_size, stack_size);
 thd->gc_cont = &entry_pt;
 thd->gc_args[0] = &clos_halt;
 thd->gc_num_args = 1;
 thd->thread_id = pthread_self();
 gc_add_mutator(thd);
 Cyc_heap_init(heap_size);
 thd->thread_state = CYC_THREAD_STATE_RUNNABLE;
 Cyc_start_trampoline(thd);
 return 0;}
